name: ci

on:
  push:
    branches:
      - "master"

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - 
        name: Install dependencies
        run: npm install
      - 
        name: Build the project
        run: npm build
      - 
        name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
      - 
        name: Test the project
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/url-shortner-app:latest
